spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=wb_schema
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: udpate
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: false
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher